### ISSUE TITLE
Reporting a potential security issue

### ISSUE THREAD

**Issue by artem-smotrakov** [Waikato/weka-trunk#21]
What is the best way to report a potential security problem in Weka? Unfortunately, I didn't find any security contact. No reply on wekalist@list.waikato.ac.nz either. Thanks!

**Comment by fracpete** [comment]
Eibe [replied](https://list.waikato.ac.nz/hyperkitty/list/wekalist@list.waikato.ac.nz/message/FVTNDNRO7CJZ2JI4MTNV67R5L4K7UJTL/) to you on the Wekalist on April 11th, but we never heard back from you.

**Comment by artem-smotrakov** [comment]
That's strange. I didn't receive that email for some reason. Anyway, I'll send the details shortly. Thanks!
