### ISSUE TITLE
How can the parameters of the model be optimized by developing a set?

### ISSUE THREAD

**Issue by CallMeByYourName** [Waikato/weka-trunk#22]
Using the training set, I obtained a trained model of a Naive Bayes classifier.

But how do I use the development set to optimize the parameters of this model? 
I did not find the corresponding command.

**Comment by fracpete** [comment]
The [NaiveBayes](https://weka.sourceforge.io/doc.dev/weka/classifiers/bayes/NaiveBayes.html) classifier only has two flags to turn on/off behavior, there isn't anything to optimize.
Please use the Weka mailing list for questions regarding Weka as per README.md.
